
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/Huawei/DevEco Studio/sdk/default/openharmony/native/build-tools/cmake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The target system is: OHOS - 1 - aarch64
      The host system is: Windows - 10.0.19045 - AMD64
...
